### ISSUE TITLE
`/compass here` not implemented?

### ISSUE THREAD

**Issue by ghost** [Philipp15b/CompassEx#1]
Installed CompassEx Build 2 for CB 1337 (md5sum 89d49d631c6981a6ca05ee11d095f404), but it appears that `/compass here` is not implemented and there isn't a compassex.here permissions node documented.

The command simply returns the help information when `/compass here` is invoked.

**Comment by Philipp15b** [comment]
`/compass here` is implemented, but for some reason I did not rebuild the jar file. Please download the new file [here](http://dev.bukkit.org/server-mods/compassex/files/3-compass-ex-build-3/). 

Please report back if you are still having problems with it.
