### ISSUE TITLE
Add Dynmap support

### ISSUE THREAD

**Issue by fahlman** [Philipp15b/CompassEx#10]
Would you consider making a companion plugin (Dynmap-CompassEx) that would allow CompassEx's saved target locations appear on a Dynmap map?

**Comment by Philipp15b** [comment]
This will probably be delayed until webbukkit/dynmap#1010 is solved.

**Comment by fahlman** [comment]
Thanks for considering this. I look forward to this feature in the future.

**Comment by Philipp15b** [comment]
Added with 74a49303000b03f6ded126788ee134a1b4b49c10.
