### ISSUE TITLE
Add Vault support?

### ISSUE THREAD

**Issue by fahlman** [Philipp15b/CompassEx#11]
Would you consider supporting Vault so creating waypoints can have a cost?

**Comment by Philipp15b** [comment]
You mean setting a global price for all to create a waypoint? Can you please specify more in detail which features you exactly want (e.g. permissions not to pay...)?

**Comment by fahlman** [comment]
Yes, a cost to use **/compass save here ID**. And maybe a cost to use **/compass publicize ID** an **/compass privatize ID** too. Permission to pay or not to pay would also be good too. Thanks for responding to my request.

**Comment by Philipp15b** [comment]
Here you go, 5c1af2edac7fac1302fe27fccd0f3d07ba5ccdcb implements this. Version 1.1.0 will be available on BukkitDev soon.
