### ISSUE TITLE
Multiple word support

### ISSUE THREAD

**Issue by fahlman** [Philipp15b/CompassEx#13]
The ability to disable CompassEx's features by world. For instance if I had a pvp world where I didn't want players to be able to use CompassEx's ability to track other players or save locations.

**Comment by Philipp15b** [comment]
I do not think that this is an appropiate feature for CompassEx. I think that this is more of a feature for permission managers. I don't know which you are using, but the great [PermissionsEx](http://dev.bukkit.org/server-mods/permissionsex/) has [support for world permissions](https://github.com/PEXPlugins/PermissionsEx/wiki/Advanced-permissions-setup#wiki-pex-multiworld).
