### ISSUE TITLE
'/compass player' command cooldown

### ISSUE THREAD

**Issue by nhoclesnar** [Philipp15b/CompassEx#17]
Please add a 'player-cooldown:' option inside the config to let users set the cooldown of '/compass player' command.

For the option, the integer should be in second, and setting it to 0 would disable cooldown.

It's because the '/compass live' command would be pointless if players can spam '/compass player' as much as they want to. By giving '/compass player' a cooldown, it would make '/compass live' much more convenient and beneficial, and therefore much more sense.

**Comment by Philipp15b** [comment]
I don't think this plugin should implement this, as it's not a useful feature for most users. There are other plugins like [this](http://dev.bukkit.org/server-mods/booscooldowns/) (haven't tried it) out there that provide a generic solution for it.
