### ISSUE TITLE
Distance to named target

### ISSUE THREAD

**Issue by fahlman** [Philipp15b/CompassEx#19]
All player to show distance to the named target in blocks.

/compass distance ID

**Comment by Philipp15b** [comment]
Couldn't this be integrated into the `/compass info` command? Or is there a reason this should be seperated?

**Comment by fahlman** [comment]
That seems like a reasonable idea too.

On Saturday, April 6, 2013, Philipp Schröer wrote:

> Couldn't this be integrated into the /compass info command? Or is there a
> reason this should be seperated?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Philipp15b/CompassEx/issues/19#issuecomment-15998455
> .

## 

Ryan Fahlsing
r.fahlsing@gmail.com

**Comment by Philipp15b** [comment]
It's now added and documented.

**Comment by Philipp15b** [comment]
Wait, sorry, wrong issue ;)
