### ISSUE TITLE
Add Dynmap support

### ISSUE THREAD

**Issue by stvncao5** [Philipp15b/CompassEx#23]
Public locations saved by CompassEx should be displayed as points on DynMap.

This is the dev.bukkit page for the DynMap plugin: http://dev.bukkit.org/bukkit-plugins/dynmap/

**Comment by fahlman** [comment]
I believe this is already implemented (https://github.com/Philipp15b/CompassEx/commit/74a49303000b03f6ded126788ee134a1b4b49c10)

**Comment by stvncao5** [comment]
Oh crap, I'm a complete idiot. >_>

Forgot I was using an old version of CompassEx.
