### ISSUE TITLE
Exceptions on startup caused by loading deathpoints.db.yml

### ISSUE THREAD

**Issue by arnefm** [Philipp15b/CompassEx#25]
I often get exceptions on startup. I have not found any clear pattern for when they appear, but I often see them in the log after a server restart. My server restart regularly (every night at 4 am).

http://hastebin.com/noqiqasena.pas

Could there be something wrong with the saving of deathpoints?

**Comment by Philipp15b** [comment]
Thanks a lot for reporting. As stated in the commit message, I'm not quite sure this fixes the problem as it seems to be a bug in Bukkit/SnakeYAML, but I hope it does.
