### ISSUE TITLE
Zero Permission Pressence

### ISSUE THREAD

**Issue by Crazdale** [Philipp15b/CompassEx#4]
So, I just tested your plugin out... I seen no hint of permissions working with this plugin... I tested on PEX and using SuperPerms... users were able to fully use this plugin, even with ZERO permissions given.  I know PEX is buggy and all, but with no permissions assigned, at all, how is it people can use any of the commands?

**Comment by Philipp15b** [comment]
There is no problem with PEX and permissions are wonderfully implemented, see for example [here](https://github.com/Philipp15b/minecraft-bukkit-compassex/blob/master/src/de/philworld/bukkit/compassex/CompassEx.java#L136). The problem that you experienced was that I gave all users these permissions by default and you would have to explicitely disallow them to use these commands.
