### ISSUE TITLE
/compass n,s,w,e point the wrong directions

### ISSUE THREAD

**Issue by davr** [Philipp15b/CompassEx#8]
I'm using the build from Mtihc (http://dev.bukkit.org/server-mods/compassex/#c23) because I wanted the /cp bed command, and didn't see a new compiled build from you yet. So it is possible this bug is only in his version.

I've done testing, here are the directions the compass points (yes N&S are the same, and E&W are the same)

N: +X
S: +X
W: +Z
E: +Z

Here is the directions they SHOULD point (note that these directions changed a couple versions back when notch moved the sun)

N: -Z
S: +Z
W: -X
E: +X

**Comment by Philipp15b** [comment]
Sorry for the delay but there seems to be a bug in Bukkit that prevents this fix from working correctly.

**Comment by Defekto** [comment]
Any Progress on this bug? Just started using this plugin, but if this can't be resolved, then it doesn't fulfill the main reason that i got this plugin.

**Comment by fahlman** [comment]
RealCompass (http://dev.bukkit.org/server-mods/realcompass/) is a mod for bukkit that will configure the compass to match cardinal directions. According to the license you can do whatever you want with the source. The source is claimed to be in the .jar. Maybe this can be a starting point?

**Comment by Philipp15b** [comment]
Thanks for the tip, @fahlman. I'll hopefully fix that today.

**Comment by fahlman** [comment]
Happy to be of assistance. I hope it helps resolve the problem.
